#pragma once
#define CMD_FIRMWARE_REQ 0x02
#define CMD_FIRMWARE_REP 0x03
#define CMD_NODE_TAG_REQ 0x06
#define CMD_NODE_TAG_REP 0x07
#define CMD_NODE_TAG_SET_REQ 0x08
#define CMD_NODE_TAG_SET_REP 0x09
#define CMD_CHANNEL_SET_REQ 0x0C
#define CMD_CHANNEL_SET_REP 0x0D
#define CMD_NODE_CONFIG_REQ 0x0E
#define CMD_NODE_CONFIG_REP 0x0F
#define CMD_LOG_DEST_REQ 0x12
#define CMD_LOG_DEST_REP 0x13
#define CMD_LOG_DEST_SET_REQ 0x14
#define CMD_LOG_DEST_SET_REP 0x15
#define CMD_REBOOT_REQ 0x18
#define CMD_REBOOT_REP 0x19

#define CMD_GROUPS_REQ 0x20
#define CMD_GROUPS_REP 0x21
#define CMD_GROUPS_SET_REQ 0x22
#define CMD_GROUPS_SET_REP 0x23
// Allocated for MeshMesh Direct
#define CMD_ENTITY_REQ 0x30
#define CMD_ENTITY_REP 0x31
// Allocated for Packet Transport
#define CMD_PACKET_TRANSPORT_REQ 0x32
#define CMD_PACKET_TRANSPORT_REP 0x33
