#ifndef _COMMANDS_H_
#define _COMMANDS_H_

#define CMD_MAGICK 0xFE
#define CMD_MAX_BUFFER_SIZE 1024

#define CMD_UART_ECHO_REQ 0x00
#define CMD_UART_ECHO_REP 0x01
#define CMD_FIRMWARE_REQ 0x02
#define CMD_FIRMWARE_REP 0x03
#define CMD_NODE_ID_REQ 0x04
#define CMD_NODE_ID_REP 0x05
#define CMD_NODE_TAG_REQ 0x06
#define CMD_NODE_TAG_REP 0x07
#define CMD_NODE_TAG_SET_REQ 0x08
#define CMD_NODE_TAG_SET_REP 0x09
#define CMD_BIND_CLEAR_REQ 0x0A
#define CMD_BIND_CLEAR_REP 0x0B
#define CMD_CHANNEL_SET_REQ 0x0C
#define CMD_CHANNEL_SET_REP 0x0D
#define CMD_NODE_CONFIG_REQ 0x0E
#define CMD_NODE_CONFIG_REP 0x0F
#define CMD_LOG_DEST_REQ 0x12
#define CMD_LOG_DEST_REP 0x13
#define CMD_LOG_DEST_SET_REQ 0x14
#define CMD_LOG_DEST_SET_REP 0x15

#define CMD_REBOOT_REQ 0x18
#define CMD_REBOOT_REP 0x19
#define CMD_DISCOVERY_REQ 0x1A
#define CMD_DISCOVERY_REP 0x1B
#define CMD_RSSICHECK_REQ 0x1C
#define CMD_RSSICHECK_REP 0x1D
#define CMD_FLASH_OPER_REQ 0x1E
#define CMD_FLASH_OPER_REP 0x1F

#define CMD_GROUPS_REQ 0x20
#define CMD_GROUPS_REP 0x21
#define CMD_GROUPS_SET_REQ 0x22
#define CMD_GROUPS_SET_REP 0x23

#define CMD_ENTITIES_COUNT_REQ 0x26
#define CMD_ENTITIES_COUNT_REP 0x27
#define CMD_ENTITY_HASH_REQ 0x28
#define CMD_ENTITY_HASH_REP 0x29
#define CMD_GET_ENTITY_STATE_REQ 0x2A
#define CMD_GET_ENTITY_STATE_REP 0x2B
#define CMD_SET_ENTITY_STATE_REQ 0x2C
#define CMD_SET_ENTITY_STATE_REP 0x2D
#define CMD_ENTITY_REQ 0x30
#define CMD_ENTITY_REP 0x31

#define CMD_LOGEVENT_REQ 0x38
#define CMD_LOGEVENT_REP 0x39

#define CMD_BROADCAST_SEND 0x70
#define CMD_BROADCAST_RECV 0x71
#define CMD_UNICAST_SEND 0x72
#define CMD_UNICAST_RECV 0x73
#define CMD_BEACONS_SEND 0x74
#define CMD_BEACONS_RECV 0x75
#define CMD_MULTIPATH_SEND 0x76
#define CMD_MULTIPATH_RECV 0x77
#define CMD_POLITEBRD_SEND 0x78
#define CMD_POLITEBRD_RECV 0x79
#define CMD_CONNPATH_REQUEST 0x7A
#define CMD_CONNPATH_REPLY 0x7B
#define CMD_FILTERED_REQUEST 0x7C
#define CMD_FILTERED_REPLY 0x7D

#define CMD_NULL_REQ 0x7E
#define CMD_ERROR_REP 0x7F

#endif /* APP_USER_COMMANDS_H_ */
